apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lbsunrise-roofing-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: lrsunrise.com  # Replace with your actual domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: lbsunrise-roofing-service
            port:
              number: 80